baseURL: https://peterambrosiussen.netlify.app/
languageCode: en-us
title: Portfolio website for Peter Ambrosiussen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: View website
    subtitle: |-  
      WELCOME TO MY PERSONALISED WEBSITE WHICH TELLS YOU MORE ABOUT MYSELF AND WHAT I HAVE LEARNED DURING THE DATA ANALYTICS FOR FINANCE COURSE
    title: Hello world, my name is Peter Ambrosiussen
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: petera.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +31 6 48 54 71 40
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Peter Ambrosiussen
    enable: yes
    quicklinks:
      #- alt: HTML5 UP
      #  text: 'Design: '
      #  url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/peter.ambrosiussen.1/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/peter.ambrosiussen/
      - icon: fa-github
        label: GitHub
        url: https://github.com/PeterAmbrosiussen
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/peter-ambrosiussen/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/Biography
      - name: CV
        url: blogs/cv
      - name: Projects
        url: blogs
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: profile_picture.png
        subtitle: A short introduction to my life
        title: Biography
        url: blogs/biography
      - image: lbs.jpg
        subtitle: My professional and academic achievements
        title: Curriculum Vitae
        url: blogs/cv
      - image: climate.jpg
        subtitle: Have weather anomalies increased over time?
        title: Climate change
        url: blogs/climate_change
      - image: Biden.jpg
        subtitle: How have Biden's approval rates developed?
        title: Joe Biden
        url: blogs/ipsum
      - image: Money.jpg
        subtitle: Can yield curves help predict recessions?
        title: Yield curve
        url: blogs/ipsum
      - image: Bike.jpg
        subtitle: Have weekly bike rentals increased over the last few years?
        title: Bike rentals
        url: blogs/ipsum
 # two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
