---
categories:
- ""
- ""
title: "Climate change and temperature anomalies"
date: ""
description: A study of how weather anomalies have increased over time, including a 95% confidence interval for the delta
draft: false
image: fire.jpg
keywords: ""
slug: climate
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<div id="research-questions" class="section level2">
<h2>Research questions:</h2>
<ol style="list-style-type: decimal">
<li>Have weather anomalies increased over time?</li>
<li>What is the Confidence Interval for delta?</li>
</ol>
</div>
<div id="source" class="section level2">
<h2>Source:</h2>
<ul>
<li><a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt" class="uri">https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt</a></li>
</ul>
</div>
<div id="underlying-analysis" class="section level2">
<h2>Underlying analysis</h2>
<div id="have-weather-anomalies-increased-over-time" class="section level3">
<h3>Have weather anomalies increased over time?</h3>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>To define temperature anomalies we need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;%
  select(Year:Dec)%&gt;% # selecting year and 12 month variables
  pivot_longer(cols=2:13, # converting dataframe to long format
               names_to =&quot;Month&quot;,
               values_to = &quot;delta&quot;)

glimpse(tidyweather)</code></pre>
<pre><code>## Rows: 1,704
## Columns: 3
## $ Year  &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880~
## $ Month &lt;chr&gt; &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;~
## $ delta &lt;dbl&gt; -0.35, -0.51, -0.23, -0.30, -0.06, -0.16, -0.18, -0.26, -0.23, -~</code></pre>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)), # add columns date, month and year
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point(size = 0.8)+ # add points
  geom_smooth(color=&quot;red&quot;) + # add trendline
  theme_bw() +
  theme(panel.border = element_blank()) +
  labs ( # change titles and axis names
    title = &quot;Weather Anomalies&quot;,
    subtitle = &quot;Temperature deviations have increased since 1880&quot;,
    x = &quot;Year&quot;,
    y = &quot;Temperature deviation in degrees Celsius&quot;
  )</code></pre>
<p><img src="/blogs/climate_files/figure-html/scatter_plot-1.png" width="1152" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point(size = 0.8)+
  geom_smooth(color=&quot;red&quot;) +
  facet_wrap(vars(month)) + # show each month individually
  theme_bw() +
  theme(panel.border = element_blank(), # remove background
        strip.background = element_blank() # remove chart title formatting for better readability
        ) +
  labs (
    title = &quot;Weather Anomalies&quot;,
    subtitle = &quot;More pronounced increases in fall and spring&quot;,
    x = &quot;Year&quot;,
    y = &quot;Temperature deviation in degrees Celsius&quot;
  )</code></pre>
<p><img src="/blogs/climate_files/figure-html/facet_wrap-1.png" width="1152" style="display: block; margin: auto;" />
Overall, it appears that the effect of increasing temperature is more pronounced in February, March, April and October. Potential explanations for the increase in February, March and April may include the significant drop in Northern Hemisphere snow cover and Arctic sea ice during these months.</p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference from the base period of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval, color = interval), legend.position = &quot;none&quot;)+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +
  theme(legend.title = element_blank(), panel.border = element_blank()) + # remove legend title
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    x = &quot;Temperature deviation in degrees Celsius&quot;, 
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="/blogs/climate_files/figure-html/intervals2-1.png" width="648" style="display: block; margin: auto;" />
So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(
    annual_average_delta = mean(delta, na.rm = TRUE)
  )

#plotting the data:
ggplot(average_annual_anomaly, aes(x = year, y = annual_average_delta))+
  geom_point(size = 1.1)+
  
  #Fit the best fit line, using LOESS method
  geom_smooth(color = &quot;red&quot;)+
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  theme(panel.border = element_blank()) +
  labs (
    title = &quot;Average Yearly Temperature Anomaly&quot;,
    x = &quot;Year&quot;,
    y = &quot;Average annual temperature deviation in degrees Celsius&quot;
  )                         </code></pre>
<p><img src="/blogs/climate_files/figure-html/averaging-1.png" width="1152" style="display: block; margin: auto;" /></p>
</div>
<div id="what-is-the-confidence-interval-for-delta" class="section level3">
<h3>What is the Confidence Interval for delta?</h3>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Our task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
 filter(date &gt;= ymd(&quot;2011-01-01&quot;), date &lt; ymd(&quot;2021-09-01&quot;)) %&gt;%
  group_by(interval) %&gt;% # group by interval to calculate statistics for entire period 2011-present
  summarise(  # calculate summary statistics for temperature deviation (delta) using summarise and stat functions
    mean_annual_delta = mean(delta), # calculate mean, SD, count, SE, lower/upper 95% CI (see this line and below)
    sd_annual_delta = sd(delta),
    count = n(),
    se_annual_delta = sd_annual_delta / sqrt(count),
    t_critical = qt(0.975, count -1),
    lower = mean_annual_delta - t_critical * se_annual_delta,
    upper = mean_annual_delta + t_critical * se_annual_delta,
  ) %&gt;% 
  select(interval, mean_annual_delta, sd_annual_delta, se_annual_delta, lower, upper) %&gt;% # select columns for table
  rename(c(&quot;Period&quot;=&quot;interval&quot;, &quot;Mean&quot;=&quot;mean_annual_delta&quot;, &quot;Standard Deviation&quot;=&quot;sd_annual_delta&quot;, &quot;Standard Error&quot;=&quot;se_annual_delta&quot;, &quot;Lower CI Border&quot;=&quot;lower&quot;, &quot;Upper CI Border&quot;=&quot;upper&quot;)) %&gt;% # rename columns
  kable(digits = 2) %&gt;% # choose two digits after comma
  kable_styling()
 
formula_ci # print</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Period
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Standard Deviation
</th>
<th style="text-align:right;">
Standard Error
</th>
<th style="text-align:right;">
Lower CI Border
</th>
<th style="text-align:right;">
Upper CI Border
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2011-present
</td>
<td style="text-align:right;">
1.06
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1.01
</td>
<td style="text-align:right;">
1.11
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
formula_ci &lt;- comparison %&gt;% 
 filter(year &gt;= &quot;2011&quot;, year &lt; &quot;2021&quot;) %&gt;% # choose the interval 2011 to 2020, as 2021 has incomplete data
  group_by(interval) %&gt;% # group by interval to calculate statistics for entire period 2011-present
  summarise(  # calculate summary statistics for temperature deviation (delta) using summarise and stat functions
    mean_annual_delta = mean(delta), # calculate mean, SD, count, SE, lower/upper 95% CI (see this line and below)
    sd_annual_delta = sd(delta),
    count = n(),
    se_annual_delta = sd_annual_delta / sqrt(count),
    t_critical = qt(0.975, count -1),
    lower = mean_annual_delta - t_critical * se_annual_delta,
    upper = mean_annual_delta + t_critical * se_annual_delta,
  ) %&gt;% 
  select(lower, upper) 
  
boot_delta &lt;- comparison %&gt;% 
  filter(year &gt;= &quot;2011&quot;, year &lt; &quot;2021&quot;) %&gt;% # filter for years 2011-present
  group_by(interval) %&gt;% 
  specify(response = delta) %&gt;% # bootstrap step 1: specify variable
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;% # bootstrap step 2: specify number of reps to generate
  calculate(stat = &quot;mean&quot;) # bootstrap step 3: choose statistic to calculate

percentile_ci &lt;- boot_delta %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;) # use get_ci to get the 95% confidence interval

visualize(boot_delta) + # visualize 
  shade_confidence_interval(endpoints = percentile_ci, color = &quot;red&quot;) +
  labs(
      title = &quot;Simulation-Based Bootstrap Distribution and Confidence Interval of Delta&quot;,
      x = &quot;Delta&quot;,
      y = &quot;Frequency&quot;
  ) +
  theme_bw() +
  theme(panel.border = element_blank())</code></pre>
<p><img src="/blogs/climate_files/figure-html/calculate_CI_using_bootstrap-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>Overall, it appears that the confidence interval for the average annual delta is between 1.01 and 1.11 degrees for 2011-present using the formula and between 1.02 and 1.11 degrees using bootstrapping. This means that if we were to take 100 random samples from the population, we are 95% certain that the mean of these samples falls between 1.01/1.02 and 1.11 degrees.The formula for computing the confidence interval is the mean delta - / + critical t-value for n-1 * standard error of delta. The bootstrapping consists of generating a bunch of bootstrap samples, finding the mean of each sample, and creating a distribution of the sample statistics of which the 95% confidence interval is the middle 95% of the bootstrap distribution. The sampling within the bootstrap samples is done with replacement.</p>
</div>
</div>
